### ISSUE TITLE
Embed VisualPlus.dll in exe file inVisual Studio Comm 2017 Ver 15.7.5 and .NET ver 4.7.03056

### ISSUE THREAD

**Issue by mathewfer** [DarkByte7/VisualPlus#75]
Can you please explain how to embed the VisualPlus.dll into .EXE file?

I use the below version and I get the below error. I add the file from "resources" folder and followed this guide - https://www.youtube.com/watch?v=fYgJMRLTc1A

Visual Studio Comm 2017 Ver 15.7.5 and .NET ver 4.7.03056

Error:

System.InvalidOperationException
  HResult=0x80131509
  Message=An error occurred creating the form. See Exception.InnerException for details.  The error is: The path is not of a legal form.
  Source=WindowsApp1
  StackTrace:
   at WindowsApp1.My.MyProject.MyForms.Create__Instance__[T](T Instance) in :line 190
   at WindowsApp1.My.MyApplication.OnCreateMainForm() in C:\Users\adam\Downloads\Project1\WindowsApp1\My Project\Application.Designer.vb:line 36
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at WindowsApp1.My.MyApplication.Main(String[] Args) in :line 81

Inner Exception 1:
ArgumentException: The path is not of a legal form.

Please let me know

Mathew

**Comment by DarkByte7** [comment]
@mathewfer My guess is its trying to use the Dll file before its extracted from the resources resulting in that error.

I haven't yet actually tested to merge it with executable applications on my other projects that use the framework and just kept it in the same folder. My plan was to use something like ILMerge eventually or have another layer application on top that runs first extract it first from resources to the same folder before it attempts to run any functions from the framework and the application that uses it.
